### ISSUE TITLE
Subir un JPG de una moto hecha de gatos amarillos

### ISSUE THREAD

**Issue by ceteco** [FiestaCeremony/Bounties-Only-Dust#1]
1. Ir a https://www.bing.com/images/create
2. Generar una moto hecha con gatos amarillos
3. Subir la imagen a este repo

**Comment by Yimo1515** [comment]
![33682b2a-4759-4fb5-9886-d2a03fbbfc7e](https://github.com/FiestaCeremony/Bounties-Only-Dust/assets/163177187/e9f53ce8-3c69-4db4-93ef-477d094e370e)

**Comment by ceteco** [comment]
No es lo que pedí, pero me sirve
